### ISSUE TITLE
Missing core docker plugin functinality

### ISSUE THREAD

**Issue by andrewmclagan** [banzaicloud/drone-kaniko#13]
Missing:

```yaml
dockerfile: path/to/Dockerfile
```
and 

```yaml
context: path/to/context
```

From the docker drone plugin

**Comment by andrewmclagan** [comment]
Upon further investigation, the issue for me was `context` does not expand environment variables.

the path `context: dir://${PWD}/path/to/context` does not resolve. Nor does the following:

```yaml
context: dir://${PWD}/path/to/context
context: dir://$PWD/path/to/context
context: dir://./path/to/context
context: dir://path/to/context
```

although this does:

```yaml
context: dir:////drone/src/path/to/context
```

absolute path. which could one day change of course.
