### ISSUE TITLE
Possible bug in upstream Kaniko affecting latest version

### ISSUE THREAD

**Issue by MatteoJoliveau** [banzaicloud/drone-kaniko#33]
**Describe the bug**
https://github.com/GoogleContainerTools/kaniko/issues/1110

Tl;dr
This happens during a `COPY . .`

```
error building image: error building stage: failed to execute command: read /drone/src/deps/absinthe/priv: is a directory
```

**Steps to reproduce the issue:**
build a docker image with the latest `banzaicloud/drone-kaniko` (e.g. omitting the image tag)

```yaml
- name: build-docker-image
    image: banzaicloud/drone-kaniko
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: my-repo
      registry: my.private-registry.com
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
```

**Expected behavior**
It should build correctly.

**Additional context**
When pinning the version to `banzaicloud/drone-kaniko:0.5.1` it does build correctly.
